[build]
  command = "npm run build"
  publish = "dist"  # Directorio donde se encuentra el contenido para desplegar

[[headers]]
  for = "/*.js"
    [headers.values]
      Content-Type = "text/javascript"
